<?php

// Register Custom Post Type
function custom_post_type() {

	$event_labels = array(
		'name'                  => _x( 'Event', 'Post Type General Name','incode'),
		'singular_name'         => _x( 'Event', 'Post Type Singular Name','incode'),
		'menu_name'             => __( 'Events','incode'),
		'name_admin_bar'        => __( 'Events','incode'),
		'archives'              => __( 'Events Archives','incode'),
		'attributes'            => __( 'Events Attributes','incode'),
		'parent_item_colon'     => __( 'Parent Event:','incode'),
		'all_items'             => __( 'All Events','incode'),
		'add_new_item'          => __( 'Add New Event','incode'),
		'add_new'               => __( 'Add New','incode'),
		'new_item'              => __( 'New Event','incode'),
		'edit_item'             => __( 'Edit Event','incode'),
		'update_item'           => __( 'Update Event','incode'),
		'view_item'             => __( 'View Event','incode'),
		'view_items'            => __( 'View Event','incode'),
		'search_items'          => __( 'Search Event','incode'),
		'not_found'             => __( 'Not found','incode'),
		'not_found_in_trash'    => __( 'Not found in Trash','incode'),
		'featured_image'        => __( 'Featured Image','incode'),
		'set_featured_image'    => __( 'Set featured image','incode'),
		'remove_featured_image' => __( 'Remove featured image','incode'),
		'use_featured_image'    => __( 'Use as featured image','incode'),
		'insert_into_item'      => __( 'Insert into Event','incode'),
		'uploaded_to_this_item' => __( 'Uploaded to this Event','incode'),
		'items_list'            => __( 'Events list','incode'),
		'items_list_navigation' => __( 'Events list navigation','incode'),
		'filter_items_list'     => __( 'Filter Events list','incode'),
	);
	$event_args = array(
		'label'                 => __( 'Event','incode'),
		'labels'                => $event_labels,
		'supports'              => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'            => array( 'Event_category'),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-archive',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
	);
	register_post_type('event', $event_args);


	$resident_labels = array(
		'name'                  => _x( 'Resident', 'Post Type General Name','incode'),
		'singular_name'         => _x( 'Resident', 'Post Type Singular Name','incode'),
		'menu_name'             => __( 'Residents','incode'),
		'name_admin_bar'        => __( 'Residents','incode'),
		'archives'              => __( 'Residents Archives','incode'),
		'attributes'            => __( 'Residents Attributes','incode'),
		'parent_item_colon'     => __( 'Parent Resident:','incode'),
		'all_items'             => __( 'All Residents','incode'),
		'add_new_item'          => __( 'Add New Resident','incode'),
		'add_new'               => __( 'Add New','incode'),
		'new_item'              => __( 'New Resident','incode'),
		'edit_item'             => __( 'Edit Resident','incode'),
		'update_item'           => __( 'Update Resident','incode'),
		'view_item'             => __( 'View Resident','incode'),
		'view_items'            => __( 'View Resident','incode'),
		'search_items'          => __( 'Search Resident','incode'),
		'not_found'             => __( 'Not found','incode'),
		'not_found_in_trash'    => __( 'Not found in Trash','incode'),
		'featured_image'        => __( 'Featured Image','incode'),
		'set_featured_image'    => __( 'Set featured image','incode'),
		'remove_featured_image' => __( 'Remove featured image','incode'),
		'use_featured_image'    => __( 'Use as featured image','incode'),
		'insert_into_item'      => __( 'Insert into Resident','incode'),
		'uploaded_to_this_item' => __( 'Uploaded to this Resident','incode'),
		'items_list'            => __( 'Residents list','incode'),
		'items_list_navigation' => __( 'Residents list navigation','incode'),
		'filter_items_list'     => __( 'Filter Residents list','incode'),
	);
	$resident_args = array(
		'label'                 => __( 'Resident','incode'),
		'labels'                => $resident_labels,
		'supports'              => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'            => array( 'resident_category'),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-admin-multisite',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
	);
	register_post_type('resident', $resident_args);



	$service_labels = array(
		'name'                  => _x( 'Service', 'Post Type General Name','incode'),
		'singular_name'         => _x( 'Service', 'Post Type Singular Name','incode'),
		'menu_name'             => __( 'Services','incode'),
		'name_admin_bar'        => __( 'Services','incode'),
		'archives'              => __( 'Services Archives','incode'),
		'attributes'            => __( 'Services Attributes','incode'),
		'parent_item_colon'     => __( 'Parent Service:','incode'),
		'all_items'             => __( 'All Services','incode'),
		'add_new_item'          => __( 'Add New Service','incode'),
		'add_new'               => __( 'Add New','incode'),
		'new_item'              => __( 'New Service','incode'),
		'edit_item'             => __( 'Edit Service','incode'),
		'update_item'           => __( 'Update Service','incode'),
		'view_item'             => __( 'View Service','incode'),
		'view_items'            => __( 'View Service','incode'),
		'search_items'          => __( 'Search Service','incode'),
		'not_found'             => __( 'Not found','incode'),
		'not_found_in_trash'    => __( 'Not found in Trash','incode'),
		'featured_image'        => __( 'Featured Image','incode'),
		'set_featured_image'    => __( 'Set featured image','incode'),
		'remove_featured_image' => __( 'Remove featured image','incode'),
		'use_featured_image'    => __( 'Use as featured image','incode'),
		'insert_into_item'      => __( 'Insert into Service','incode'),
		'uploaded_to_this_item' => __( 'Uploaded to this Service','incode'),
		'items_list'            => __( 'Services list','incode'),
		'items_list_navigation' => __( 'Services list navigation','incode'),
		'filter_items_list'     => __( 'Filter Services list','incode'),
	);
	$service_args = array(
		'label'                 => __( 'Service','incode'),
		'labels'                => $service_labels,
		'supports'              => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'            => array( 'service_category'),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-image-filter',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
	);
	register_post_type('service', $service_args);

}
add_action( 'init', 'custom_post_type', 0 );
